<?php
/**
 * GetAPaystub200Response
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Check API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-04-04
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetAPaystub200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAPaystub200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_a_paystub_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payroll' => 'string',
        'payday' => 'string',
        'period_start' => 'string',
        'period_end' => 'string',
        'company' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompany',
        'void_of' => 'mixed',
        'voided_by' => 'mixed',
        'employee' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployee',
        'earnings' => '\OpenAPI\Client\Model\GetAPaystub200ResponseEarningsInner[]',
        'reimbursements' => 'mixed[]',
        'employee_taxes' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployeeTaxesInner[]',
        'company_taxes' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompanyTaxesInner[]',
        'employee_benefit_contributions' => 'mixed[]',
        'company_benefit_contributions' => 'mixed[]',
        'post_tax_deductions' => 'mixed[]',
        'summary' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerSummary',
        'time_off_balances' => '\OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerTimeOffBalances',
        'payment_method' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payroll' => null,
        'payday' => null,
        'period_start' => null,
        'period_end' => null,
        'company' => null,
        'void_of' => null,
        'voided_by' => null,
        'employee' => null,
        'earnings' => null,
        'reimbursements' => null,
        'employee_taxes' => null,
        'company_taxes' => null,
        'employee_benefit_contributions' => null,
        'company_benefit_contributions' => null,
        'post_tax_deductions' => null,
        'summary' => null,
        'time_off_balances' => null,
        'payment_method' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payroll' => false,
        'payday' => false,
        'period_start' => false,
        'period_end' => false,
        'company' => false,
        'void_of' => true,
        'voided_by' => true,
        'employee' => false,
        'earnings' => false,
        'reimbursements' => false,
        'employee_taxes' => false,
        'company_taxes' => false,
        'employee_benefit_contributions' => false,
        'company_benefit_contributions' => false,
        'post_tax_deductions' => false,
        'summary' => false,
        'time_off_balances' => false,
        'payment_method' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payroll' => 'payroll',
        'payday' => 'payday',
        'period_start' => 'period_start',
        'period_end' => 'period_end',
        'company' => 'company',
        'void_of' => 'void_of',
        'voided_by' => 'voided_by',
        'employee' => 'employee',
        'earnings' => 'earnings',
        'reimbursements' => 'reimbursements',
        'employee_taxes' => 'employee_taxes',
        'company_taxes' => 'company_taxes',
        'employee_benefit_contributions' => 'employee_benefit_contributions',
        'company_benefit_contributions' => 'company_benefit_contributions',
        'post_tax_deductions' => 'post_tax_deductions',
        'summary' => 'summary',
        'time_off_balances' => 'time_off_balances',
        'payment_method' => 'payment_method'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payroll' => 'setPayroll',
        'payday' => 'setPayday',
        'period_start' => 'setPeriodStart',
        'period_end' => 'setPeriodEnd',
        'company' => 'setCompany',
        'void_of' => 'setVoidOf',
        'voided_by' => 'setVoidedBy',
        'employee' => 'setEmployee',
        'earnings' => 'setEarnings',
        'reimbursements' => 'setReimbursements',
        'employee_taxes' => 'setEmployeeTaxes',
        'company_taxes' => 'setCompanyTaxes',
        'employee_benefit_contributions' => 'setEmployeeBenefitContributions',
        'company_benefit_contributions' => 'setCompanyBenefitContributions',
        'post_tax_deductions' => 'setPostTaxDeductions',
        'summary' => 'setSummary',
        'time_off_balances' => 'setTimeOffBalances',
        'payment_method' => 'setPaymentMethod'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payroll' => 'getPayroll',
        'payday' => 'getPayday',
        'period_start' => 'getPeriodStart',
        'period_end' => 'getPeriodEnd',
        'company' => 'getCompany',
        'void_of' => 'getVoidOf',
        'voided_by' => 'getVoidedBy',
        'employee' => 'getEmployee',
        'earnings' => 'getEarnings',
        'reimbursements' => 'getReimbursements',
        'employee_taxes' => 'getEmployeeTaxes',
        'company_taxes' => 'getCompanyTaxes',
        'employee_benefit_contributions' => 'getEmployeeBenefitContributions',
        'company_benefit_contributions' => 'getCompanyBenefitContributions',
        'post_tax_deductions' => 'getPostTaxDeductions',
        'summary' => 'getSummary',
        'time_off_balances' => 'getTimeOffBalances',
        'payment_method' => 'getPaymentMethod'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('payroll', $data ?? [], null);
        $this->setIfExists('payday', $data ?? [], null);
        $this->setIfExists('period_start', $data ?? [], null);
        $this->setIfExists('period_end', $data ?? [], null);
        $this->setIfExists('company', $data ?? [], null);
        $this->setIfExists('void_of', $data ?? [], null);
        $this->setIfExists('voided_by', $data ?? [], null);
        $this->setIfExists('employee', $data ?? [], null);
        $this->setIfExists('earnings', $data ?? [], null);
        $this->setIfExists('reimbursements', $data ?? [], null);
        $this->setIfExists('employee_taxes', $data ?? [], null);
        $this->setIfExists('company_taxes', $data ?? [], null);
        $this->setIfExists('employee_benefit_contributions', $data ?? [], null);
        $this->setIfExists('company_benefit_contributions', $data ?? [], null);
        $this->setIfExists('post_tax_deductions', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('time_off_balances', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payroll
     *
     * @return string|null
     */
    public function getPayroll()
    {
        return $this->container['payroll'];
    }

    /**
     * Sets payroll
     *
     * @param string|null $payroll payroll
     *
     * @return self
     */
    public function setPayroll($payroll)
    {
        if (is_null($payroll)) {
            throw new \InvalidArgumentException('non-nullable payroll cannot be null');
        }
        $this->container['payroll'] = $payroll;

        return $this;
    }

    /**
     * Gets payday
     *
     * @return string|null
     */
    public function getPayday()
    {
        return $this->container['payday'];
    }

    /**
     * Sets payday
     *
     * @param string|null $payday payday
     *
     * @return self
     */
    public function setPayday($payday)
    {
        if (is_null($payday)) {
            throw new \InvalidArgumentException('non-nullable payday cannot be null');
        }
        $this->container['payday'] = $payday;

        return $this;
    }

    /**
     * Gets period_start
     *
     * @return string|null
     */
    public function getPeriodStart()
    {
        return $this->container['period_start'];
    }

    /**
     * Sets period_start
     *
     * @param string|null $period_start period_start
     *
     * @return self
     */
    public function setPeriodStart($period_start)
    {
        if (is_null($period_start)) {
            throw new \InvalidArgumentException('non-nullable period_start cannot be null');
        }
        $this->container['period_start'] = $period_start;

        return $this;
    }

    /**
     * Gets period_end
     *
     * @return string|null
     */
    public function getPeriodEnd()
    {
        return $this->container['period_end'];
    }

    /**
     * Sets period_end
     *
     * @param string|null $period_end period_end
     *
     * @return self
     */
    public function setPeriodEnd($period_end)
    {
        if (is_null($period_end)) {
            throw new \InvalidArgumentException('non-nullable period_end cannot be null');
        }
        $this->container['period_end'] = $period_end;

        return $this;
    }

    /**
     * Gets company
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompany|null
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompany|null $company company
     *
     * @return self
     */
    public function setCompany($company)
    {
        if (is_null($company)) {
            throw new \InvalidArgumentException('non-nullable company cannot be null');
        }
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets void_of
     *
     * @return mixed|null
     */
    public function getVoidOf()
    {
        return $this->container['void_of'];
    }

    /**
     * Sets void_of
     *
     * @param mixed|null $void_of void_of
     *
     * @return self
     */
    public function setVoidOf($void_of)
    {
        if (is_null($void_of)) {
            array_push($this->openAPINullablesSetToNull, 'void_of');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('void_of', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['void_of'] = $void_of;

        return $this;
    }

    /**
     * Gets voided_by
     *
     * @return mixed|null
     */
    public function getVoidedBy()
    {
        return $this->container['voided_by'];
    }

    /**
     * Sets voided_by
     *
     * @param mixed|null $voided_by voided_by
     *
     * @return self
     */
    public function setVoidedBy($voided_by)
    {
        if (is_null($voided_by)) {
            array_push($this->openAPINullablesSetToNull, 'voided_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('voided_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['voided_by'] = $voided_by;

        return $this;
    }

    /**
     * Gets employee
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployee|null
     */
    public function getEmployee()
    {
        return $this->container['employee'];
    }

    /**
     * Sets employee
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployee|null $employee employee
     *
     * @return self
     */
    public function setEmployee($employee)
    {
        if (is_null($employee)) {
            throw new \InvalidArgumentException('non-nullable employee cannot be null');
        }
        $this->container['employee'] = $employee;

        return $this;
    }

    /**
     * Gets earnings
     *
     * @return \OpenAPI\Client\Model\GetAPaystub200ResponseEarningsInner[]|null
     */
    public function getEarnings()
    {
        return $this->container['earnings'];
    }

    /**
     * Sets earnings
     *
     * @param \OpenAPI\Client\Model\GetAPaystub200ResponseEarningsInner[]|null $earnings earnings
     *
     * @return self
     */
    public function setEarnings($earnings)
    {
        if (is_null($earnings)) {
            throw new \InvalidArgumentException('non-nullable earnings cannot be null');
        }
        $this->container['earnings'] = $earnings;

        return $this;
    }

    /**
     * Gets reimbursements
     *
     * @return mixed[]|null
     */
    public function getReimbursements()
    {
        return $this->container['reimbursements'];
    }

    /**
     * Sets reimbursements
     *
     * @param mixed[]|null $reimbursements reimbursements
     *
     * @return self
     */
    public function setReimbursements($reimbursements)
    {
        if (is_null($reimbursements)) {
            throw new \InvalidArgumentException('non-nullable reimbursements cannot be null');
        }
        $this->container['reimbursements'] = $reimbursements;

        return $this;
    }

    /**
     * Gets employee_taxes
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployeeTaxesInner[]|null
     */
    public function getEmployeeTaxes()
    {
        return $this->container['employee_taxes'];
    }

    /**
     * Sets employee_taxes
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerEmployeeTaxesInner[]|null $employee_taxes employee_taxes
     *
     * @return self
     */
    public function setEmployeeTaxes($employee_taxes)
    {
        if (is_null($employee_taxes)) {
            throw new \InvalidArgumentException('non-nullable employee_taxes cannot be null');
        }
        $this->container['employee_taxes'] = $employee_taxes;

        return $this;
    }

    /**
     * Gets company_taxes
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompanyTaxesInner[]|null
     */
    public function getCompanyTaxes()
    {
        return $this->container['company_taxes'];
    }

    /**
     * Sets company_taxes
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerCompanyTaxesInner[]|null $company_taxes company_taxes
     *
     * @return self
     */
    public function setCompanyTaxes($company_taxes)
    {
        if (is_null($company_taxes)) {
            throw new \InvalidArgumentException('non-nullable company_taxes cannot be null');
        }
        $this->container['company_taxes'] = $company_taxes;

        return $this;
    }

    /**
     * Gets employee_benefit_contributions
     *
     * @return mixed[]|null
     */
    public function getEmployeeBenefitContributions()
    {
        return $this->container['employee_benefit_contributions'];
    }

    /**
     * Sets employee_benefit_contributions
     *
     * @param mixed[]|null $employee_benefit_contributions employee_benefit_contributions
     *
     * @return self
     */
    public function setEmployeeBenefitContributions($employee_benefit_contributions)
    {
        if (is_null($employee_benefit_contributions)) {
            throw new \InvalidArgumentException('non-nullable employee_benefit_contributions cannot be null');
        }
        $this->container['employee_benefit_contributions'] = $employee_benefit_contributions;

        return $this;
    }

    /**
     * Gets company_benefit_contributions
     *
     * @return mixed[]|null
     */
    public function getCompanyBenefitContributions()
    {
        return $this->container['company_benefit_contributions'];
    }

    /**
     * Sets company_benefit_contributions
     *
     * @param mixed[]|null $company_benefit_contributions company_benefit_contributions
     *
     * @return self
     */
    public function setCompanyBenefitContributions($company_benefit_contributions)
    {
        if (is_null($company_benefit_contributions)) {
            throw new \InvalidArgumentException('non-nullable company_benefit_contributions cannot be null');
        }
        $this->container['company_benefit_contributions'] = $company_benefit_contributions;

        return $this;
    }

    /**
     * Gets post_tax_deductions
     *
     * @return mixed[]|null
     */
    public function getPostTaxDeductions()
    {
        return $this->container['post_tax_deductions'];
    }

    /**
     * Sets post_tax_deductions
     *
     * @param mixed[]|null $post_tax_deductions post_tax_deductions
     *
     * @return self
     */
    public function setPostTaxDeductions($post_tax_deductions)
    {
        if (is_null($post_tax_deductions)) {
            throw new \InvalidArgumentException('non-nullable post_tax_deductions cannot be null');
        }
        $this->container['post_tax_deductions'] = $post_tax_deductions;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerSummary|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerSummary|null $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets time_off_balances
     *
     * @return \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerTimeOffBalances|null
     */
    public function getTimeOffBalances()
    {
        return $this->container['time_off_balances'];
    }

    /**
     * Sets time_off_balances
     *
     * @param \OpenAPI\Client\Model\GetAnEmployeesPaystubs200ResponseResultsInnerTimeOffBalances|null $time_off_balances time_off_balances
     *
     * @return self
     */
    public function setTimeOffBalances($time_off_balances)
    {
        if (is_null($time_off_balances)) {
            throw new \InvalidArgumentException('non-nullable time_off_balances cannot be null');
        }
        $this->container['time_off_balances'] = $time_off_balances;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string|null
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string|null $payment_method payment_method
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


