<?php
/**
 * CreateTheEnrollmentProfileRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Check API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-04-04
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateTheEnrollmentProfileRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateTheEnrollmentProfileRequest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateTheEnrollmentProfileRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTheEnrollmentProfileRequest"
     */
    public function testCreateTheEnrollmentProfileRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "employee_count"
     */
    public function testPropertyEmployeeCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contractor_count"
     */
    public function testPropertyContractorCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pay_period_amount"
     */
    public function testPropertyPayPeriodAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "previous_payroll_provider"
     */
    public function testPropertyPreviousPayrollProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_payroll"
     */
    public function testPropertyFirstPayroll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_payroll_of_year"
     */
    public function testPropertyFirstPayrollOfYear()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_since"
     */
    public function testPropertyUserSince()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expected_first_payday"
     */
    public function testPropertyExpectedFirstPayday()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "approved_for_payment_processing"
     */
    public function testPropertyApprovedForPaymentProcessing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "existing_payroll_customer_processing_period"
     */
    public function testPropertyExistingPayrollCustomerProcessingPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_monthly_revenue"
     */
    public function testPropertyAverageMonthlyRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "earliest_known_revenue"
     */
    public function testPropertyEarliestKnownRevenue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "months_on_previous_payroll_provider"
     */
    public function testPropertyMonthsOnPreviousPayrollProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "social_media"
     */
    public function testPropertySocialMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "products_actively_used"
     */
    public function testPropertyProductsActivelyUsed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_contacts"
     */
    public function testPropertyAccountContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fraud_score"
     */
    public function testPropertyFraudScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "predicted_fraud"
     */
    public function testPropertyPredictedFraud()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paying_user"
     */
    public function testPropertyPayingUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "missed_payments_count"
     */
    public function testPropertyMissedPaymentsCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payroll_history_access_method"
     */
    public function testPropertyPayrollHistoryAccessMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "implementation_services_submission_comment"
     */
    public function testPropertyImplementationServicesSubmissionComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
